### PR TITLE
use enums

### PR DESCRIPTION
**Pull request by adsharma**

### CODE REVIEW

**Comment by andreas-abel** [comment]
This has no obvious advantage over the existing code.

**Comment by adsharma** [comment]
A straightforward benefit is type safety

https://paste.ubuntu.com/p/z8qFWXN7wR/

Of course more specific types need to be defined for every class of
registers.

**Comment by andreas-abel** [comment]
And obvious downsides in this case are that it reduces readability, frequently calling "all(cls)" likely reduces performance, and it makes the code completely inconsistent if only general-purpose registers are represented as enums but other register types are not.

Your modification
``` class RegOperand:
-    def __init__(self, reg, isImplicitStackOperand=False):
+    def __init__(self, reg: GPRegs, isImplicitStackOperand=False):
         self.reg = reg
         self.isImplicitStackOperand = isImplicitStackOperand
```

is wrong. This is not limited to GPRegs but needs to be able to store other kinds of registers that it gets as a string from XED.

**Comment by adsharma** [comment]
And if perf of all() is a concern, you could add a @lru_cache decorator so
it would be computed once.

**Comment by andreas-abel** [comment]
> This is a great argument for actually using types. It wasn't obvious to me by reading the code what the type of `reg` should be. 

The type of `reg` should be string. This way, all the registers returned by XED (including ones that I am not aware of and ones that will be added in the future) can be handled. 

>Of course, all other register types should be represented as enums IMO.

Representing all register types as enums would require a lot of work and provide only comparably little benefit. There are many other things that have a much higher priority right now.

If you would like to contribute by adding new microarchitectural models, or by improving the existing ones, or by fixing actual bugs (that lead to a crash or incorrect results), or by adding new functionality, I will be happy to review your pull requests. I will not review pull requests that only make minor cosmetic changes.

**Pull request closed without merging**
